version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_username
      MONGO_INITDB_ROOT_PASSWORD: db_password
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: db_username
      ME_CONFIG_MONGODB_ADMINPASSWORD: db_password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
